using AccBotWizard.ViewModels;

namespace AccBotWizard.Services;

public class DockerDeploymentService : IDeploymentService
{
    public async Task<bool> DeployAsync(WizardData data, Action<string> logCallback)
    {
        logCallback("Generating Docker configuration files...");
        await Task.Delay(500);

        var dockerCompose = GenerateDockerCompose(data);
        var envFile = GenerateEnvFile(data);

        logCallback("Docker files generated successfully!");
        logCallback("");
        logCallback("Files created:");
        logCallback("  - docker-compose.yml");
        logCallback("  - .env");
        logCallback("");
        logCallback("To start the bot, run:");
        logCallback("  docker-compose up -d");

        return true;
    }

    public string GenerateDockerCompose(WizardData data)
    {
        return $@"version: '3.8'

services:
  accbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accbot-{data.BotName.ToLower()}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - accbot-data:/app/data
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  # Optional: Local CosmosDB emulator replacement
  mongodb:
    image: mongo:7
    container_name: accbot-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

volumes:
  accbot-data:
  mongodb-data:
";
    }

    public string GenerateEnvFile(WizardData data)
    {
        var credentials = GetCredentialEnvVars(data);

        return $@"# AccBot Configuration
# Generated by AccBot Wizard

# General Settings
Name={data.BotName}
ExchangeName={data.SelectedExchange}
Currency={data.Currency}
Fiat={data.Fiat}
ChunkSize={data.ChunkSize}

# Schedule (NCRONTAB format)
# Every {data.HourDivider} hour(s)
DayDividerSchedule=0 0 */{data.HourDivider} * * *

# Withdrawal Settings
WithdrawalEnabled={data.WithdrawalEnabled.ToString().ToLower()}
WithdrawalAddress={data.WithdrawalAddress}
MaxWithdrawalPercentageFee={data.MaxWithdrawalPercentageFee}

# Telegram Settings
TelegramChannel={data.TelegramChannel}
TelegramBot={data.TelegramBotToken}

# Database Settings (use MongoDB for Docker deployment)
# CosmosDbEndpointUri=
# CosmosDbPrimaryKey=
MONGODB_CONNECTION_STRING=mongodb://mongodb:27017

# Exchange Credentials
{credentials}
";
    }

    private string GetCredentialEnvVars(WizardData data)
    {
        var lines = new List<string>();

        switch (data.SelectedExchange)
        {
            case "coinmate":
                lines.Add($"CoinMateCredentials_ClientId={data.Credentials.GetValueOrDefault("ClientId", "")}");
                lines.Add($"CoinMateCredentials_PublicKey={data.Credentials.GetValueOrDefault("PublicKey", "")}");
                lines.Add($"CoinMateCredentials_PrivateKey={data.Credentials.GetValueOrDefault("PrivateKey", "")}");
                break;
            case "binance":
                lines.Add($"BinanceCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"BinanceCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                break;
            case "kraken":
                lines.Add($"KrakenCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"KrakenCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                break;
            case "huobi":
                lines.Add($"HuobiCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"HuobiCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                break;
            case "kucoin":
                lines.Add($"KuCoinCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"KuCoinCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                lines.Add($"KuCoinCredentials_PassPhrase={data.Credentials.GetValueOrDefault("PassPhrase", "")}");
                break;
            case "bitfinex":
                lines.Add($"BitfinexCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"BitfinexCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                break;
            case "coinbase":
                lines.Add($"CoinbaseCredentials_Key={data.Credentials.GetValueOrDefault("Key", "")}");
                lines.Add($"CoinbaseCredentials_Secret={data.Credentials.GetValueOrDefault("Secret", "")}");
                break;
        }

        return string.Join(Environment.NewLine, lines);
    }
}
